### ISSUE TITLE
update photos

### ISSUE THREAD

**Issue by KonradHoeffner** [Onto-Med/top.de#9]
Use pictures from the IMISE brochure, credit photographer.

**Comment by KonradHoeffner** [comment]
@Yagnap: Sieht schon mal super aus aber bitte noch das Gruppenfoto komprimieren, das sind momentan 2,5 MB. Und die Portraits können etwas größer angezeigt werden.

**Comment by KonradHoeffner** [comment]
@Yagnap: Und oben bei Alex steht noch der Photographenhinweis, den dann nach unten.

**Comment by Yagnap** [comment]
Fixed in 1b21439
